services:
  authservice:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    depends_on:
      - dbservice
    networks:
      - app-network
    restart: unless-stopped

  dbservice:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=authdb
    ports:
      - '5432:5432'
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
  
  dbaudit:
    image: postgres:13
    environment:
      - POSTGRES_USER=audit
      - POSTGRES_PASSWORD=auditpassword
      - POSTGRES_DB=auditdb
    ports:
      - '5433:5432'
    volumes:
      - audit-db-data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped


volumes:
  auth-db-data:
  audit-db-data:

networks:
  app-network:
    driver: bridge
